-- ═══ COACH LOOP · 2026-09-08 ═══
-- Idempotent. Run in the Supabase SQL editor once after deploying this build.
--
-- 1. program.version: the app and the Coach keep a stored program only while it
--    was written for the block the code ships (PROG.version in lib/engine.mjs).
alter table public.program add column if not exists version text;

-- 2. program_updates: audit log of every coach/settings change. The Coach applies
--    changes directly to `settings` / `program`; the app reads this table to
--    toast what changed and lists it under Setup → Coach changes.
create table if not exists public.program_updates (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now()
);
alter table public.program_updates add column if not exists type text;
alter table public.program_updates add column if not exists action text;
alter table public.program_updates add column if not exists payload text;
alter table public.program_updates add column if not exists reason text;
alter table public.program_updates add column if not exists applied boolean default false;
alter table public.program_updates add column if not exists applied_at timestamptz;
alter table public.program_updates add column if not exists source text;
alter table public.program_updates add column if not exists summary text;

-- 3. body_measurements: tape measurements were local-only; the Coach needs them.
create table if not exists public.body_measurements (date date primary key);
alter table public.body_measurements add column if not exists chest numeric;
alter table public.body_measurements add column if not exists waist numeric;
alter table public.body_measurements add column if not exists arm_l numeric;
alter table public.body_measurements add column if not exists arm_r numeric;
alter table public.body_measurements add column if not exists thigh_l numeric;
alter table public.body_measurements add column if not exists thigh_r numeric;

-- 4. recovery.source (Oura writes it; the app now round-trips it).
alter table public.recovery add column if not exists source text;

-- 5. lytes (fast-day electrolytes) in case 2026-07-26-lytes.sql was skipped.
create table if not exists public.lytes (date date primary key);
alter table public.lytes add column if not exists na integer;
alter table public.lytes add column if not exists k integer;
alter table public.lytes add column if not exists mg integer;

-- Report
select table_name, string_agg(column_name, ', ' order by ordinal_position) as columns
  from information_schema.columns where table_schema='public'
   and table_name in ('program','program_updates','body_measurements','recovery','lytes')
  group by table_name order by table_name;
